# Generated by Django 3.2.2 on 2021-05-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_payment_price', models.CharField(max_length=150)),
                ('user_payment_product', models.CharField(max_length=50)),
                ('user_payment_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserPocket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_income_date1', models.DateField()),
                ('user_income_date2', models.DateField()),
                ('user_income_date3', models.DateField()),
                ('user_income_date4', models.DateField()),
                ('user_taxes_date', models.DateField()),
                ('user_income', models.CharField(max_length=150)),
                ('user_income2', models.CharField(max_length=150)),
                ('user_income3', models.CharField(max_length=150)),
                ('user_income4', models.CharField(max_length=150)),
                ('user_expense_rent', models.CharField(max_length=150)),
                ('user_expense_housing', models.CharField(max_length=150)),
                ('user_expense_transportation', models.CharField(max_length=150)),
                ('user_expense_education', models.CharField(max_length=150)),
                ('user_expense_personal_family', models.CharField(max_length=150)),
                ('user_expense_health_care', models.CharField(max_length=150)),
                ('user_expense_other', models.CharField(max_length=150)),
                ('user_budget_food', models.CharField(max_length=150)),
                ('user_budget_wants', models.CharField(max_length=150)),
                ('user_budget_investments', models.CharField(max_length=150)),
                ('user_budget_emergency', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_mood', models.CharField(max_length=50)),
                ('status_energy', models.CharField(max_length=50)),
                ('status_sleep_day', models.IntegerField()),
            ],
        ),
    ]
