# Generated by Django 3.2.2 on 2021-05-26 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210526_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpayment',
            name='budget_name',
        ),
        migrations.AddField(
            model_name='userpayment',
            name='budget',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='home.budget'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
