# Generated by Django 3.2.2 on 2021-05-26 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210526_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.RemoveField(
            model_name='task',
            name='extend_user',
        ),
        migrations.RemoveField(
            model_name='userpayment',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='userpocket',
            name='budgets',
        ),
        migrations.RemoveField(
            model_name='userpocket',
            name='expenses',
        ),
        migrations.RemoveField(
            model_name='userpocket',
            name='incomes',
        ),
        migrations.RemoveField(
            model_name='userpocket',
            name='payment',
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskCategory',
        ),
        migrations.DeleteModel(
            name='UserPayment',
        ),
        migrations.DeleteModel(
            name='UserPocket',
        ),
    ]
